/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWithdrawRouteImport } from './routes/_app/withdraw'
import { Route as AppWalletsRouteImport } from './routes/_app/wallets'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSendRouteImport } from './routes/_app/send'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMarketRouteImport } from './routes/_app/market'
import { Route as AppKycRouteImport } from './routes/_app/kyc'
import { Route as AppFundRouteImport } from './routes/_app/fund'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAbanRouteImport } from './routes/_app/aban'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWalletsRoute = AppWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSendRoute = AppSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKycRoute = AppKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFundRoute = AppFundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAbanRoute = AppAbanRouteImport.update({
  id: '/aban',
  path: '/aban',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/aban': typeof AppAbanRoute
  '/dashboard': typeof AppDashboardRoute
  '/fund': typeof AppFundRoute
  '/kyc': typeof AppKycRoute
  '/market': typeof AppMarketRoute
  '/profile': typeof AppProfileRoute
  '/send': typeof AppSendRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/wallets': typeof AppWalletsRoute
  '/withdraw': typeof AppWithdrawRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/aban': typeof AppAbanRoute
  '/dashboard': typeof AppDashboardRoute
  '/fund': typeof AppFundRoute
  '/kyc': typeof AppKycRoute
  '/market': typeof AppMarketRoute
  '/profile': typeof AppProfileRoute
  '/send': typeof AppSendRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/wallets': typeof AppWalletsRoute
  '/withdraw': typeof AppWithdrawRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/aban': typeof AppAbanRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fund': typeof AppFundRoute
  '/_app/kyc': typeof AppKycRoute
  '/_app/market': typeof AppMarketRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/send': typeof AppSendRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/wallets': typeof AppWalletsRoute
  '/_app/withdraw': typeof AppWithdrawRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/aban'
    | '/dashboard'
    | '/fund'
    | '/kyc'
    | '/market'
    | '/profile'
    | '/send'
    | '/settings'
    | '/transactions'
    | '/wallets'
    | '/withdraw'
    | '/api/public/paystack-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/aban'
    | '/dashboard'
    | '/fund'
    | '/kyc'
    | '/market'
    | '/profile'
    | '/send'
    | '/settings'
    | '/transactions'
    | '/wallets'
    | '/withdraw'
    | '/api/public/paystack-webhook'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/_app/aban'
    | '/_app/dashboard'
    | '/_app/fund'
    | '/_app/kyc'
    | '/_app/market'
    | '/_app/profile'
    | '/_app/send'
    | '/_app/settings'
    | '/_app/transactions'
    | '/_app/wallets'
    | '/_app/withdraw'
    | '/api/public/paystack-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/withdraw': {
      id: '/_app/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/wallets': {
      id: '/_app/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AppWalletsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/send': {
      id: '/_app/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AppSendRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/market': {
      id: '/_app/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/kyc': {
      id: '/_app/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AppKycRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/fund': {
      id: '/_app/fund'
      path: '/fund'
      fullPath: '/fund'
      preLoaderRoute: typeof AppFundRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/aban': {
      id: '/_app/aban'
      path: '/aban'
      fullPath: '/aban'
      preLoaderRoute: typeof AppAbanRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppAbanRoute: typeof AppAbanRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFundRoute: typeof AppFundRoute
  AppKycRoute: typeof AppKycRoute
  AppMarketRoute: typeof AppMarketRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSendRoute: typeof AppSendRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppWalletsRoute: typeof AppWalletsRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAbanRoute: AppAbanRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFundRoute: AppFundRoute,
  AppKycRoute: AppKycRoute,
  AppMarketRoute: AppMarketRoute,
  AppProfileRoute: AppProfileRoute,
  AppSendRoute: AppSendRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppWalletsRoute: AppWalletsRoute,
  AppWithdrawRoute: AppWithdrawRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
