/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWithdrawRouteImport } from './routes/_app/withdraw'
import { Route as AppWalletsRouteImport } from './routes/_app/wallets'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSendRouteImport } from './routes/_app/send'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMarketRouteImport } from './routes/_app/market'
import { Route as AppKycRouteImport } from './routes/_app/kyc'
import { Route as AppFundRouteImport } from './routes/_app/fund'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppAbanRouteImport } from './routes/_app/aban'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as ApiPublicIntasendWebhookRouteImport } from './routes/api/public/intasend-webhook'
import { Route as ApiPublicDarajaStkCallbackRouteImport } from './routes/api/public/daraja-stk-callback'
import { Route as ApiPublicDarajaB2cTimeoutRouteImport } from './routes/api/public/daraja-b2c-timeout'
import { Route as ApiPublicDarajaB2cResultRouteImport } from './routes/api/public/daraja-b2c-result'
import { Route as AppAdminWithdrawalsRouteImport } from './routes/_app/admin/withdrawals'
import { Route as AppAdminWalletsRouteImport } from './routes/_app/admin/wallets'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminTransactionsRouteImport } from './routes/_app/admin/transactions'
import { Route as AppAdminSecurityRouteImport } from './routes/_app/admin/security'
import { Route as AppAdminRatesRouteImport } from './routes/_app/admin/rates'
import { Route as AppAdminKycRouteImport } from './routes/_app/admin/kyc'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin/audit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWalletsRoute = AppWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSendRoute = AppSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKycRoute = AppKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFundRoute = AppFundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAbanRoute = AppAbanRouteImport.update({
  id: '/aban',
  path: '/aban',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntasendWebhookRoute =
  ApiPublicIntasendWebhookRouteImport.update({
    id: '/api/public/intasend-webhook',
    path: '/api/public/intasend-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDarajaStkCallbackRoute =
  ApiPublicDarajaStkCallbackRouteImport.update({
    id: '/api/public/daraja-stk-callback',
    path: '/api/public/daraja-stk-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDarajaB2cTimeoutRoute =
  ApiPublicDarajaB2cTimeoutRouteImport.update({
    id: '/api/public/daraja-b2c-timeout',
    path: '/api/public/daraja-b2c-timeout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDarajaB2cResultRoute =
  ApiPublicDarajaB2cResultRouteImport.update({
    id: '/api/public/daraja-b2c-result',
    path: '/api/public/daraja-b2c-result',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAdminWithdrawalsRoute = AppAdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminWalletsRoute = AppAdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTransactionsRoute = AppAdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSecurityRoute = AppAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRatesRoute = AppAdminRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminKycRoute = AppAdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/aban': typeof AppAbanRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/fund': typeof AppFundRoute
  '/kyc': typeof AppKycRoute
  '/market': typeof AppMarketRoute
  '/profile': typeof AppProfileRoute
  '/send': typeof AppSendRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/wallets': typeof AppWalletsRoute
  '/withdraw': typeof AppWithdrawRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/kyc': typeof AppAdminKycRoute
  '/admin/rates': typeof AppAdminRatesRoute
  '/admin/security': typeof AppAdminSecurityRoute
  '/admin/transactions': typeof AppAdminTransactionsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/wallets': typeof AppAdminWalletsRoute
  '/admin/withdrawals': typeof AppAdminWithdrawalsRoute
  '/api/public/daraja-b2c-result': typeof ApiPublicDarajaB2cResultRoute
  '/api/public/daraja-b2c-timeout': typeof ApiPublicDarajaB2cTimeoutRoute
  '/api/public/daraja-stk-callback': typeof ApiPublicDarajaStkCallbackRoute
  '/api/public/intasend-webhook': typeof ApiPublicIntasendWebhookRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/aban': typeof AppAbanRoute
  '/dashboard': typeof AppDashboardRoute
  '/fund': typeof AppFundRoute
  '/kyc': typeof AppKycRoute
  '/market': typeof AppMarketRoute
  '/profile': typeof AppProfileRoute
  '/send': typeof AppSendRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/wallets': typeof AppWalletsRoute
  '/withdraw': typeof AppWithdrawRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/kyc': typeof AppAdminKycRoute
  '/admin/rates': typeof AppAdminRatesRoute
  '/admin/security': typeof AppAdminSecurityRoute
  '/admin/transactions': typeof AppAdminTransactionsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/wallets': typeof AppAdminWalletsRoute
  '/admin/withdrawals': typeof AppAdminWithdrawalsRoute
  '/api/public/daraja-b2c-result': typeof ApiPublicDarajaB2cResultRoute
  '/api/public/daraja-b2c-timeout': typeof ApiPublicDarajaB2cTimeoutRoute
  '/api/public/daraja-stk-callback': typeof ApiPublicDarajaStkCallbackRoute
  '/api/public/intasend-webhook': typeof ApiPublicIntasendWebhookRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/aban': typeof AppAbanRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fund': typeof AppFundRoute
  '/_app/kyc': typeof AppKycRoute
  '/_app/market': typeof AppMarketRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/send': typeof AppSendRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/wallets': typeof AppWalletsRoute
  '/_app/withdraw': typeof AppWithdrawRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/kyc': typeof AppAdminKycRoute
  '/_app/admin/rates': typeof AppAdminRatesRoute
  '/_app/admin/security': typeof AppAdminSecurityRoute
  '/_app/admin/transactions': typeof AppAdminTransactionsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/admin/wallets': typeof AppAdminWalletsRoute
  '/_app/admin/withdrawals': typeof AppAdminWithdrawalsRoute
  '/api/public/daraja-b2c-result': typeof ApiPublicDarajaB2cResultRoute
  '/api/public/daraja-b2c-timeout': typeof ApiPublicDarajaB2cTimeoutRoute
  '/api/public/daraja-stk-callback': typeof ApiPublicDarajaStkCallbackRoute
  '/api/public/intasend-webhook': typeof ApiPublicIntasendWebhookRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/_app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/aban'
    | '/admin'
    | '/dashboard'
    | '/fund'
    | '/kyc'
    | '/market'
    | '/profile'
    | '/send'
    | '/settings'
    | '/transactions'
    | '/wallets'
    | '/withdraw'
    | '/admin/audit'
    | '/admin/kyc'
    | '/admin/rates'
    | '/admin/security'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/api/public/daraja-b2c-result'
    | '/api/public/daraja-b2c-timeout'
    | '/api/public/daraja-stk-callback'
    | '/api/public/intasend-webhook'
    | '/api/public/paystack-webhook'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/aban'
    | '/dashboard'
    | '/fund'
    | '/kyc'
    | '/market'
    | '/profile'
    | '/send'
    | '/settings'
    | '/transactions'
    | '/wallets'
    | '/withdraw'
    | '/admin/audit'
    | '/admin/kyc'
    | '/admin/rates'
    | '/admin/security'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/api/public/daraja-b2c-result'
    | '/api/public/daraja-b2c-timeout'
    | '/api/public/daraja-stk-callback'
    | '/api/public/intasend-webhook'
    | '/api/public/paystack-webhook'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/_app/aban'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/fund'
    | '/_app/kyc'
    | '/_app/market'
    | '/_app/profile'
    | '/_app/send'
    | '/_app/settings'
    | '/_app/transactions'
    | '/_app/wallets'
    | '/_app/withdraw'
    | '/_app/admin/audit'
    | '/_app/admin/kyc'
    | '/_app/admin/rates'
    | '/_app/admin/security'
    | '/_app/admin/transactions'
    | '/_app/admin/users'
    | '/_app/admin/wallets'
    | '/_app/admin/withdrawals'
    | '/api/public/daraja-b2c-result'
    | '/api/public/daraja-b2c-timeout'
    | '/api/public/daraja-stk-callback'
    | '/api/public/intasend-webhook'
    | '/api/public/paystack-webhook'
    | '/_app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicDarajaB2cResultRoute: typeof ApiPublicDarajaB2cResultRoute
  ApiPublicDarajaB2cTimeoutRoute: typeof ApiPublicDarajaB2cTimeoutRoute
  ApiPublicDarajaStkCallbackRoute: typeof ApiPublicDarajaStkCallbackRoute
  ApiPublicIntasendWebhookRoute: typeof ApiPublicIntasendWebhookRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/withdraw': {
      id: '/_app/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/wallets': {
      id: '/_app/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AppWalletsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/send': {
      id: '/_app/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AppSendRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/market': {
      id: '/_app/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/kyc': {
      id: '/_app/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AppKycRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/fund': {
      id: '/_app/fund'
      path: '/fund'
      fullPath: '/fund'
      preLoaderRoute: typeof AppFundRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/aban': {
      id: '/_app/aban'
      path: '/aban'
      fullPath: '/aban'
      preLoaderRoute: typeof AppAbanRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/intasend-webhook': {
      id: '/api/public/intasend-webhook'
      path: '/api/public/intasend-webhook'
      fullPath: '/api/public/intasend-webhook'
      preLoaderRoute: typeof ApiPublicIntasendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daraja-stk-callback': {
      id: '/api/public/daraja-stk-callback'
      path: '/api/public/daraja-stk-callback'
      fullPath: '/api/public/daraja-stk-callback'
      preLoaderRoute: typeof ApiPublicDarajaStkCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daraja-b2c-timeout': {
      id: '/api/public/daraja-b2c-timeout'
      path: '/api/public/daraja-b2c-timeout'
      fullPath: '/api/public/daraja-b2c-timeout'
      preLoaderRoute: typeof ApiPublicDarajaB2cTimeoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daraja-b2c-result': {
      id: '/api/public/daraja-b2c-result'
      path: '/api/public/daraja-b2c-result'
      fullPath: '/api/public/daraja-b2c-result'
      preLoaderRoute: typeof ApiPublicDarajaB2cResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/withdrawals': {
      id: '/_app/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AppAdminWithdrawalsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/wallets': {
      id: '/_app/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AppAdminWalletsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/transactions': {
      id: '/_app/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AppAdminTransactionsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/security': {
      id: '/_app/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AppAdminSecurityRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/rates': {
      id: '/_app/admin/rates'
      path: '/rates'
      fullPath: '/admin/rates'
      preLoaderRoute: typeof AppAdminRatesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/kyc': {
      id: '/_app/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AppAdminKycRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminKycRoute: typeof AppAdminKycRoute
  AppAdminRatesRoute: typeof AppAdminRatesRoute
  AppAdminSecurityRoute: typeof AppAdminSecurityRoute
  AppAdminTransactionsRoute: typeof AppAdminTransactionsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminWalletsRoute: typeof AppAdminWalletsRoute
  AppAdminWithdrawalsRoute: typeof AppAdminWithdrawalsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminKycRoute: AppAdminKycRoute,
  AppAdminRatesRoute: AppAdminRatesRoute,
  AppAdminSecurityRoute: AppAdminSecurityRoute,
  AppAdminTransactionsRoute: AppAdminTransactionsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminWalletsRoute: AppAdminWalletsRoute,
  AppAdminWithdrawalsRoute: AppAdminWithdrawalsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteRouteChildren {
  AppAbanRoute: typeof AppAbanRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppFundRoute: typeof AppFundRoute
  AppKycRoute: typeof AppKycRoute
  AppMarketRoute: typeof AppMarketRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSendRoute: typeof AppSendRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppWalletsRoute: typeof AppWalletsRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAbanRoute: AppAbanRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppFundRoute: AppFundRoute,
  AppKycRoute: AppKycRoute,
  AppMarketRoute: AppMarketRoute,
  AppProfileRoute: AppProfileRoute,
  AppSendRoute: AppSendRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppWalletsRoute: AppWalletsRoute,
  AppWithdrawRoute: AppWithdrawRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicDarajaB2cResultRoute: ApiPublicDarajaB2cResultRoute,
  ApiPublicDarajaB2cTimeoutRoute: ApiPublicDarajaB2cTimeoutRoute,
  ApiPublicDarajaStkCallbackRoute: ApiPublicDarajaStkCallbackRoute,
  ApiPublicIntasendWebhookRoute: ApiPublicIntasendWebhookRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
